### ISSUE TITLE
Return of option "-a" / invoking as "mad" possible?

### ISSUE THREAD

**Issue by fluffig** [rrthomas/mmv#15] opened 2023-10-01 16:54 UTC
Glad to see, that this old piece of software has found a new maintainer!

I'm using mmv for years now making excessive use of mad to append single files to one big "masterfile". As I updated a storage System to Debian 12 I realized that this option is not supported anymore.

Is there a reason for that? I read something about lost sourcecode in late '90-s but the former stable builds were dated ~2003 I guess. Is there any chance to get back this option? I didn't find anything similar to that tool. Everything else would make me write a lot more code like for-loops and a bunch of checks.

**Comment by rrthomas** [comment] 2023-10-01 18:44
I removed the `mad` command to simplify the code as it didn't seem useful to me.

I'll have a look to see how hard it would be to restore.

**Comment by rrthomas** [comment] 2023-10-02 17:24
It didn't seem to be very hard! I have restored `mad`. Please could you test it? Although all I basically did was revert the commit that removed the code, I had to perform the editing manually, having reorganized the code since then, so it may be that I got something wrong.

**Comment by fluffig** [comment] 2023-10-06 12:13
Thanks for your very fast reaction! I'll test the code a.s.a.p. and give you reply if it works.

**Comment by rrthomas** [comment] 2023-11-01 17:09
Sorry, I didn't see this update.

**Comment by rrthomas** [comment] 2023-11-01 17:28
Actually, it works fine when invoked normally as a program on your `PATH`. The problem is another bug (which I'll fix, thanks): namely, the name detection only works when the full program path in its invocation is just `mad` etc. If you invoke it as `./mad` it doesn't work (and the same for other names).

**Comment by rrthomas** [comment] 2023-11-01 17:37
I've pushed a fix for the problem you experienced; please could you try it?

**Closed** 2024-02-12 19:45 UTC
